Fix unjustified warning about casing for directory entries
codehaus-plexus/plexus-archiver pull request #155
Opened 2020-10-24 08:50 UTC by mthmulders

Follow-up for #128, where we omitted the case that an archive entry could be a directory. In that case, its name will end with `/`, but the canonical target path will not have the `/` suffix. This would be seen as a difference in casing, but that is not true.

2020-10-24 11:46 UTC, michael-o requested changes

2020-10-24 11:46 UTC, michael-o commented on src/test/java/org/codehaus/plexus/archiver/AbstractUnArchiverTest.java
> +        Date entryDate = new Date( System.currentTimeMillis() );
This argument is redundant.

2020-10-24 12:09 UTC, mthmulders commented on src/test/java/org/codehaus/plexus/archiver/AbstractUnArchiverTest.java
> +        Date entryDate = new Date( System.currentTimeMillis() );
It is. Resolved.

2020-10-26 08:46 UTC, michael-o approved these changes

2020-10-30 07:03 UTC, mthmulders commented
Thanks @michael-o for the review. I don't have rights to merge this PR, I'd be grateful if someone who does have the rights can merge it for me.

2021-01-12 06:12 UTC, mthmulders commented
@michael-o I see a lot of Maven components already updating Plexus Archiver, with this little issue still present. Shouldn't we try to merge this in, too, given the false warnings that'll occur otherwise?

2021-01-27 19:25 UTC, plamentotev commented
@mthmulders would you please squash the commits into one and I'll merge it.

2021-01-27 19:33 UTC, mthmulders commented
> @mthmulders would you please squash the commits into one and I'll merge it.

Squashed & force-pushed. Thanks in advance :-)

2021-01-27 20:19 UTC, merged

2021-01-28 11:35 UTC, plamentotev commented
The build is failing after the merge. I'll check it later today

2021-01-28 11:51 UTC, mthmulders commented
> Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project plexus-archiver: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.shared:maven-shared-incremental:jar:1.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar: Connection reset -> [Help 1]

My guess is that's unrelated to the code change, but feel free to investigate further and let me know if you draw a different conclusion.

2021-01-28 13:18 UTC, michael-o commented
> 
> 
> > Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project plexus-archiver: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.shared:maven-shared-incremental:jar:1.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar: Connection reset -> [Help 1]
> 
> My guess is that's unrelated to the code change, but feel free to investigate further and let me know if you draw a different conclusion.

Correct, is an ephemeral network issue. Restart or check your internet connection.

2021-01-30 07:29 UTC, plamentotev commented
@mthmulders I've released a new version with this fix. Thanks for contributing.

2021-01-30 15:24 UTC, mthmulders commented
Thank you for considering this contribution and for releasing a new version so quickly.