Ensure that if entryName contains / char they are replaced by "File.separator"
codehaus-plexus/plexus-archiver pull request #180
Opened 2021-08-18 19:35 UTC by cedmail

Since updating to plexus archiver 4.2.5 (from version 2) we have seen those warning:
[WARNING] Archive entry 'META-INF/MANIFEST.MF' and existing file 'C:\Dev\rt\master\tomcat\webapps\jahia\META-INF\MANIFEST.MF' names differ only by case. This may lead to an unexpected outcome on case-insensitive filesystems.

Issue here is that the AbtractUnArchiver assumes entryName is just a file but in a ZipArchive entryName can be a path and so when evaluating if we should extract, we should replace "/" char (Zip always use "/" by spec) by the File OS separator

2021-08-19 06:21 UTC, michael-o requested changes
This is weird. The message is about case, not file separator. Maybe this needs improvement?

2021-08-19 06:21 UTC, michael-o commented on src/test/java/org/codehaus/plexus/archiver/AbstractUnArchiverTest.java
> +        File file = new File( temporaryFolder.getRoot() + File.separator + "folder", "whatever.txt" ); // does not create the file!
directory, not folrder.

2021-08-22 18:11 UTC, plamentotev commented
> This is weird. The message is about case, not file separator. Maybe this needs improvement?

The current code assumes that if canonical path (relative to the destination directory) is not the same as entry name, then the only cause of the difference could be that the files are with different cases. Which does not seems to be always true.

One improvement that we can do is do add additional check - if the  canonical path (relative to the destination directory) is not the same as entry name, compare them but this time case insensitive. This will eliminate the false positives in case we have missed some other normalization that may cause the two names to be different. But I wonder if it will introduce additional false negatives. 

@cedmail just to be sure my understanding is correct. Even with the current version the file is extracted properly, just a warning is printed, right? Or there is issue with the extracted file. And I guess the warning is showed then the file system separator is not the same as the one user in the zip file, right?

2021-08-22 18:15 UTC, plamentotev commented
And interestingly enough the windows tests cases are failing.

2021-08-25 10:21 UTC, cedmail commented
> > This is weird. The message is about case, not file separator. Maybe this needs improvement?
> 
> The current code assumes that if canonical path (relative to the destination directory) is not the same as entry name, then the only cause of the difference could be that the files are with different cases. Which does not seems to be always true.
> 
> One improvement that we can do is do add additional check - if the canonical path (relative to the destination directory) is not the same as entry name, compare them but this time case insensitive. This will eliminate the false positives in case we have missed some other normalization that may cause the two names to be different. But I wonder if it will introduce additional false negatives.
> 
> @cedmail just to be sure my understanding is correct. Even with the current version the file is extracted properly, just a warning is printed, right? Or there is issue with the extracted file. And I guess the warning is showed then the file system separator is not the same as the one user in the zip file, right?

@plamentotev Yes the issue is that when unarchive a file of type zip (WAR) into a Windows system, it works smoothly it target directory is empty, but if you repeat the operation you get a warning for every file in archive (thousands of them)

2021-12-30 19:55 UTC, michael-o commented
@plamentotev Do we want to settle this for the next version?`

2022-01-23 16:16 UTC, plamentotev commented
> @plamentotev Do we want to settle this for the next version?`

I didn't have to look at it. I'll try to look into it this or next week.

2022-11-30 10:49 UTC, in-fke commented
This really spams the log a lot. Any chance to fix this?

2022-12-23 13:41 UTC, Bananeweizen commented on src/main/java/org/codehaus/plexus/archiver/AbstractUnArchiver.java
> +        boolean differentCasing = !entryName.replace("/", File.separator).equals( relativeCanonicalDestPath );
This change is wrong. Both strings would need to have "/" be replaced by File.separator if you want to look for different casing.

2022-12-31 19:34 UTC, closed without merging